=== Kushal121/xml-catalog/catalog_19032171.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Page">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="BackGroundImage">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="Logo"/>
							<xs:element name="Store">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="StoreName"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:string" name="Slogan"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Body">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="AboutStore"/>
							<xs:element name="Song" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Block1">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="Image1" minOccurs="0"/>
													<xs:element type="xs:string" name="Image2" minOccurs="0"/>
													<xs:element type="xs:string" name="Image3" minOccurs="0"/>
													<xs:element type="xs:string" name="Image4" minOccurs="0"/>
													<xs:element type="xs:string" name="Image5" minOccurs="0"/>
													<xs:element type="xs:string" name="Image6" minOccurs="0"/>
													<xs:element type="xs:string" name="Image7" minOccurs="0"/>
													<xs:element type="xs:string" name="Image8" minOccurs="0"/>
													<xs:element type="xs:string" name="Image9" minOccurs="0"/>
													<xs:element type="xs:string" name="Image10" minOccurs="0"/>
													<xs:element type="xs:string" name="Image11" minOccurs="0"/>
													<xs:element type="xs:string" name="Image12" minOccurs="0"/>
													<xs:element type="xs:string" name="Image13" minOccurs="0"/>
													<xs:element type="xs:string" name="Image14" minOccurs="0"/>
													<xs:element type="xs:string" name="Image15" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Block2">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="SongsDetail1">
														<xs:complexType>
															<xs:sequence>
																<xs:element type="xs:string" name="h2"/>
																<xs:element name="Song">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element type="xs:string" name="Review" minOccurs="0">
                                      </xs:element>
																			<xs:element name="Genre">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element type="xs:string" name="Review" minOccurs="0"/>
																						<xs:element type="xs:string" name="SongName"/>
																						<xs:element type="xs:string" name="GenreName"/>
																						<xs:element type="xs:string" name="Country"/>
																						<xs:element type="xs:string" name="Producer"/>
																						<xs:element type="xs:string" name="SongWriters"/>
																						<xs:element type="xs:string" name="Label"/>
																						<xs:element type="xs:string" name="Studio"/>
																					</xs:sequence>
																					<xs:attribute type="xs:string" name="Name" use="optional"/>
																					<xs:attribute type="xs:string" name="Genre_ID" use="optional"/>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																		<xs:attribute type="xs:string" name="SongID" use="optional"/>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="SongsDetail2">
														<xs:complexType>
															<xs:sequence>
																<xs:element type="xs:string" name="Singers"/>
																<xs:element type="xs:string" name="FeatBy"/>
																<xs:element type="xs:string" name="NoofArtists"/>
																<xs:element name="ReleaseYear">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element type="xs:string" name="Year"/>
																			<xs:element type="xs:string" name="Month"/>
																			<xs:element type="xs:string" name="Day"/>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element type="xs:string" name="Recorded"/>
																<xs:element type="xs:string" name="SongLength"/>
																<xs:element type="xs:string" name="Album"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element type="xs:string" name="Int1" minOccurs="0"/>
													<xs:element type="xs:string" name="Int2" minOccurs="0"/>
													<xs:element type="xs:string" name="Int3" minOccurs="0"/>
													<xs:element type="xs:string" name="Int4" minOccurs="0"/>
													<xs:element type="xs:string" name="Int5" minOccurs="0"/>
													<xs:element type="xs:string" name="Int6" minOccurs="0"/>
													<xs:element type="xs:string" name="Int7" minOccurs="0"/>
													<xs:element type="xs:string" name="Int8" minOccurs="0"/>
													<xs:element type="xs:string" name="Int9" minOccurs="0"/>
													<xs:element type="xs:string" name="Int10" minOccurs="0"/>
													<xs:element type="xs:string" name="Int11" minOccurs="0"/>
													<xs:element type="xs:string" name="Int12" minOccurs="0"/>
													<xs:element type="xs:string" name="Int13" minOccurs="0"/>
													<xs:element type="xs:string" name="Int14" minOccurs="0"/>
													<xs:element type="xs:string" name="Int15" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:float" name="ID" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Footer">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="Logo"/>
							<xs:element name="Container">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="Address"/>
										<xs:element type="xs:string" name="Contact.Number"/>
										<xs:element type="xs:string" name="WebsiteURL"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:string" name="Follow"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Kushal121/xml-catalog/catalog_19032171.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="catalog_19032171.css"?>
<Page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_19032171.xsd">
	<BackGroundImage>
		<Logo/>
		<Store>
			<StoreName>Nepal Music Store</StoreName>
		</Store>
		<Slogan>If the Music is too loud you’re too old.</Slogan>
	</BackGroundImage>
	<Body>
		<AboutStore>
							Nepal Music Store has various types of music where you can come and relax and listen to various types of music such as jazz, rock, country music, pop and dubstep.
							You bring your friends and family to listen and enjoy the music and relax in your own cabinet. It's the best music store you can find in all kathmandu valley.
							</AboutStore>
		<Song ID=" 01">
			<Block1>
				<Image1/>
			</Block1>
			<Block2>
				<SongsDetail1>
					<h2>Song Details</h2>
					<Song SongID="S1">
						<!--genre_id required-->
						<Genre Name="Jazz" Genre_ID="J1">
							<Review>⭐⭐⭐⭐⭐</Review>
							<SongName>SongName: Mischief </SongName>
							<GenreName>	Genre: Jazz</GenreName>
							<Country>Country: USA</Country>
							<Producer>Producer Name: Matt Pierson</Producer>
							<SongWriters>Song Writer: Brad Mehldau, Brian Blade</SongWriters>
							<Label>Label: Warner Bros</Label>
							<Studio>Studio: Power Station, New York City</Studio>
						</Genre>
					</Song>
				</SongsDetail1>
				<SongsDetail2>
					<Singers>Singers: Joshua Redman</Singers>
					<FeatBy>Feat By: Christian McBride</FeatBy>
					<NoofArtists>No of Artists: 4</NoofArtists>
					<ReleaseYear>
						<Year>Year: 1994</Year>
						<Month>Month: January</Month>
						<Day>Day: 15</Day>
					</ReleaseYear>
					<Recorded>Recorded: March 8-10,1994</Recorded>
					<SongLength>Song Length: 69.39</SongLength>
					<Album>Album: MoodSwing</Album>
				</SongsDetail2>
				<Int1/>
			</Block2>
		</Song>
		<Song ID=" 02">
			<Block1>
				<Image2/>
			</Block1>
			<Block2>
				<SongsDetail1>
					<h2>Song Details</h2>
					<Song SongID="S2">
						<!--genre_id required-->
						<Genre Name="Rock" Genre_ID="R1">
							<Review>⭐⭐⭐⭐⭐</Review>
							<SongName>SongName: American Girl</SongName>
							<GenreName>Genre: Rock</GenreName>
							<Country>Country: US</Country>
							<Producer>Producer Name: Denny Cordell</Producer>
							<SongWriters>Song Writer: Tom Petty</SongWriters>
							<Label>Label: Shelter</Label>
							<Studio>Studio: Shelter Studios, Hollywood</Studio>
						</Genre>
					</Song>
				</SongsDetail1>
				<SongsDetail2>
					<Singers>Singer: Tom Petty</Singers>
					<FeatBy>Feat By: The Heartbreakers</FeatBy>
					<NoofArtists>No of Artists: 2</NoofArtists>
					<ReleaseYear>
						<Year>Year: 1977</Year>
						<Month>Month: February</Month>
						<Day>Day: 21</Day>
					</ReleaseYear>
					<Recorded>Recorded: July 4,1976</Recorded>
					<SongLength>Length: 3.35</SongLength>
					<Album>Album: Tom Petty and The Heartbreakers </Album>
				</SongsDetail2>
				<Int2/>
			</Block2>
		</Song>
		<Song ID=" 03">
			<Block1>
				<Image3/>
			</Block1>
			<Block2>
				<SongsDetail1>
					<h2>Song Details</h2>
					<Song SongID="S3">
						<Review>⭐⭐⭐⭐⭐</Review>
						<!--genre_id required-->
						<Genre Name="Country Music" Genre_ID="CM1">
							<SongName>SongName: The Good Ones</SongName>
							<GenreName>Genre: Country Music</GenreName>
							<Country>Country: USA</Country>
							<Producer>Producer Name: Zach Kale, Ross Copperman</Producer>
							<SongWriters>Song Writer: Gabby Barrett, Zach Kale, Emily Landis</SongWriters>
							<Label>Label: Warner Music Nashville</Label>
							<Studio>Studio: Goldmine Studios</Studio>
						</Genre>
					</Song>
				</SongsDetail1>
				<SongsDetail2>
					<Singers>Singer: Gabby Barrett</Singers>
					<FeatBy>Feat By: Zach Kale</FeatBy>
					<NoofArtists>No of Artists: 3</NoofArtists>
					<ReleaseYear>
						<Year>Year: 2020</Year>
						<Month>Month: June</Month>
						<Day>Day: 08</Day>
					</ReleaseYear>
					<Recorded>Recorded: July 12,2020</Recorded>
					<SongLength>Song Length: 3.33</SongLength>
					<Album>Album: Gabby Barrett</Album>
				</SongsDetail2>
				<Int3/>
			</Block2>
		</Song>
		<Song ID=" 04">
			<Block1>
				<Image4/>
			</Block1>
			<Block2>
				<SongsDetail1>
					<h2>Song Details</h2>
					<Song SongID="S4">
						<!--genre_id required-->
						<Genre Name="Pop" Genre_ID="P1">
							<Review>⭐⭐⭐⭐⭐</Review>
							<SongName>Song Name: Loved By You</SongName>
							<GenreName>Genre: Pop</GenreName>
							<Country>Country: Canada</Country>
							<Producer>Producer Name: Louis Bell, Jon Bellion, Benny Blanco, Tommy Brown, Steven Franks</Producer>
							<SongWriters>Song Writer: Ashley Boyd, Jason Boyd</SongWriters>
							<Label>Label: Def Jam, RBMG, SB Projects, Schoolboy, Universal Music</Label>
							<Studio>Studio: Henson Recording Studio</Studio>
						</Genre>
					</Song>
				</SongsDetail1>
				<SongsDetail2>
					<Singers>Singer: Justin Bieber, Burna Boy</Singers>
					<FeatBy>Feat By: Burna Boy</FeatBy>
					<NoofArtists>No of Artists: 2</NoofArtists>
					<ReleaseYear>
						<Year>Year: 2021</Year>
						<Month>Month: March</Month>
						<Day>Day: 19</Day>
					</ReleaseYear>
					<Recorded>Recorded: 2019-2020</Recorded>
					<SongLength>Song Length: 2.39</SongLength>
					<Album>Album: Justice</Album>
				</SongsDetail2>
				<Int4/>
			</Block2>
		</Song>
		<Song ID=" 05">
			<Block1>
				<Image5/>
			</Block1>
			<Block2>
				<SongsDetail1>
					<h2>Song Details</h2>
					<Song SongID="S5">
						<!--genre_id required-->
						<Review>⭐⭐⭐⭐⭐</Review>
						<Genre Name="Dubstep" Genre_ID="D1">
							<SongName>Song Name: I Need Air</SongName>
							<GenreName>Genre: Dubstep</GenreName>
							<Country>Country: UK</Country>
							<Producer>Producer Name: Magnetic Man</Producer>
							<SongWriters>Song Writer: Arthur Smith, Angela Hunte, Beni Adejumo, Oliver Jones</SongWriters>
							<Label>Label: Sony,Columbia</Label>
							<Studio>Studio: Electronic Music Project</Studio>
						</Genre>
					</Song>
				</SongsDetail1>
				<SongsDetail2>
					<Singers>Singer: Magnetic Man</Singers>
					<FeatBy>Feat By: Angela Hunte</FeatBy>
					<NoofArtists>No of Artists: 2</NoofArtists>
					<ReleaseYear>
						<Year>Year: 2010</Year>
						<Month>Month: July</Month>
						<Day>Day: 23</Day>
					</ReleaseYear>
					<Recorded>Recorded: August 12,2010</Recorded>
					<SongLength>Song Length: 4.18</SongLength>
					<Album>Album: Magnetic Man</Album>
				</SongsDetail2>
				<Int5/>
			</Block2>
		</Song>
		<Song ID=" 06">
			<Block1>
				<Image6/>
			</Block1>
			<Block2>
				<SongsDetail1>
					<h2>Song Details</h2>
					<Song SongID="S6">
						<Review>⭐⭐⭐⭐⭐</Review>
						<!--genre_id required-->
						<Genre Name="Pop" Genre_ID="P1">
							<SongName>SongName: Happier</SongName>
							<GenreName>Genre: Pop</GenreName>
							<Country>Country: USA</Country>
							<Producer>Producer Name: Marshmello</Producer>
							<SongWriters>Song Writer: Christopher Comstock, Dan Smith, Steve Mac</SongWriters>
							<Label>Label: Astralwerks</Label>
							<Studio>Studio: Goldmine Studios</Studio>
						</Genre>
					</Song>
				</SongsDetail1>
				<SongsDetail2>
					<Singers>Singer: Marshmello</Singers>
					<FeatBy>Feat By: Bastille</FeatBy>
					<NoofArtists>No of Artists: 2</NoofArtists>
					<ReleaseYear>
						<Year>Year: 2018</Year>
						<Month>Month: August</Month>
						<Day>Day: 17</Day>
					</ReleaseYear>
					<Recorded>Recorded: September 12,2020</Recorded>
					<SongLength>Song Length: 3.34</SongLength>
					<Album>Album: Happier</Album>
				</SongsDetail2>
				<Int6/>
			</Block2>
		</Song>
		<Song ID=" 07">
			<Block1>
				<Image7/>
			</Block1>
			<Block2>
				<SongsDetail1>
					<h2>Song Details</h2>
					<Song SongID="S7">
						<Review>⭐⭐⭐⭐⭐</Review>
						<!--genre_id required-->
						<Genre Name="Pop" Genre_ID="P1">
							<SongName>SongName: Boy With Luv</SongName>
							<GenreName>Genre: K-Pop</GenreName>
							<Country>Country: South Korea</Country>
							<Producer>Producer Name: Pdogg</Producer>
							<SongWriters>Song Writer: Pdogg, RM, Melanie Joy, Michel Lindgren</SongWriters>
							<Label>Label: Big Hit</Label>
							<Studio>Studio: Dogg Bounce, South Korea, Mixstar, Virginia Beach</Studio>
						</Genre>
					</Song>
				</SongsDetail1>
				<SongsDetail2>
					<Singers>Singer: BTS</Singers>
					<FeatBy>Feat By: Halsey</FeatBy>
					<NoofArtists>No of Artists: 2</NoofArtists>
					<ReleaseYear>
						<Year>Year: 2019</Year>
						<Month>Month: April</Month>
						<Day>Day: 12</Day>
					</ReleaseYear>
					<Recorded>Recorded: May 09,2019</Recorded>
					<SongLength>Song Length: 3.49</SongLength>
					<Album>Album: Map of the Soul: Persona</Album>
				</SongsDetail2>
				<Int7/>
			</Block2>
		</Song>
		<Song ID=" 08">
			<Block1>
				<Image8/>
			</Block1>
			<Block2>
				<SongsDetail1>
					<h2>Song Details</h2>
					<Song SongID="S8">
						<Review>⭐⭐⭐⭐⭐</Review>
						<!--genre_id required-->
						<Genre Name="Pop" Genre_ID="P1">
							<SongName>SongName: Rockabye</SongName>
							<GenreName>Genre: Pop</GenreName>
							<Country>Country: UK</Country>
							<Producer>Producer Name: Jack Patterson, Mark Ralph, Steve Mac</Producer>
							<SongWriters>Song Writer: Jack Patterson, Anne-Marie, Ina Wroldsen, Sean Paul, Ammar Malik</SongWriters>
							<Label>Label: Atlantic, Warner</Label>
							<Studio>Studio: Club Ralph, London, The Crypt Studio, London, Rokstone Studios, London</Studio>
						</Genre>
					</Song>
				</SongsDetail1>
				<SongsDetail2>
					<Singers>Singer: Clean Bandit</Singers>
